spring.application.name=kindbridge

spring.data.mongodb.uri=mongodb+srv://cb232923_db_user:2rE8Hb3GTnUvMjIJ@kindbridge.c6jylt5.mongodb.net/kindbridge?retryWrites=true&w=majority&appName=kindbridge

server.port=8080

jwt.secret=VGhpc0lzTXlWZXJ5U2VjcmV0S2V5Rm9yS2luZEJyaWRnZUFwcGxpY2F0aW9uMTIzNDU2Nzg5
jwt.expiration=86400000

razorpay.key=YOUR_KEY_ID
razorpay.secret=YOUR_SECRET_KEY

cloudinary.cloud-name=YOUR_CLOUD_NAME

cloudinary.api-key=YOUR_API_KEY

cloudinary.api-secret=YOUR_API_SECRET


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=buddasreelatha90@gmail.com
spring.mail.password=ewqaivxrcrkgxjty

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true